# https://docs.qmk.fm/#/config_options?id=the-rulesmk-file
BOOTMAGIC_ENABLE = full
COMBO_ENABLE = yes
COMMAND_ENABLE = no
RGBLIGHT_ENABLE = no
STENO_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = yes
